services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: case
            MYSQL_USER: user
            MYSQL_PASSWORD: 123
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
